---
  extends: "@dosomething/eslint-config"
  env:
    es6: true
  globals:
    # Support fetch mechanism through isomorphic-fetch module
    fetch: true
  parserOptions:
    # Node requires 'use strict' to use built-in ES6 compatibility.
    # Use script source type, so lint doesn't throw error:
    # 'use strict' is unnecessary inside of modules.
    sourceType: script
    # Latest ECMA
    ecmaVersion: 2017
  rules:
    # We don't use babel here, so require 'use strict'.
    # See https://git.io/vr6I0.
    strict:
      - error
      - global
    # Comma dangle in functions is not yet supported in Node 7
    comma-dangle:
      - error
      - arrays: always-multiline
        objects: always-multiline
        imports: always-multiline
        exports: always-multiline
        functions: ignore
